<form action="/users" method="post">
  <div>
    <label>
      ID
      <input type="text"  name="user[id]" value="<?= htmlspecialchars($user['id']) ?>">
    </label>
    </div>
  <div>
    <label>
      Nickname
      <input type="text" required name="user[nickname]">
    </label>
    </div>
  <div>
    <label>
        Email
    <input type="email" required name="user[email]">
    </label>
    </div>
  <div>
    <label>
<input type="submit" value="Sign Up">
</form>
